import Link from "next/link";
import { createClient } from "../../lib/supabase/server";
import WorkspaceNav from "../_components/WorkspaceNav";
export default async function Finance({searchParams}:{searchParams:Promise<{org?:string}>}) {
 const p=await searchParams,s=await createClient(),{data:orgs}=await s.rpc("my_organizations"),o=orgs?.find((x:{id:string})=>x.id===p.org)||orgs?.[0];
 if(!o)return <main className="main"><div className="card"><h1 className="title">Finance</h1><Link className="button" href="/onboarding">Create organization</Link></div></main>;
 const {data:rows}=await s.from("finance_transactions").select("id,transaction_type,category,description,amount,transaction_date").eq("organization_id",o.id).order("transaction_date",{ascending:false}).limit(100);
 const income=(rows||[]).filter((x:{transaction_type:string})=>x.transaction_type==="income").reduce((a,x)=>a+Number(x.amount),0),expense=(rows||[]).filter((x:{transaction_type:string})=>x.transaction_type==="expense").reduce((a,x)=>a+Number(x.amount),0);
 return <main className="main" style={{marginLeft:0,width:"100%",maxWidth:1100,margin:"0 auto"}}><div className="topbar"><div><div className="eyebrow">Finance</div><h1 className="title">{o.name}</h1><div className="subtitle">Income, expenses and financial records.</div></div><div style={{display:"flex",gap:8}}><Link className="button" href={"/finance/new?org="+o.id}>Record transaction</Link><Link className="button secondary" href={"/dashboard?org="+o.id}>Dashboard</Link></div></div><div className="grid"><div className="card"><div className="muted">Income</div><div className="metric">{o.currency} {income.toLocaleString()}</div></div><div className="card"><div className="muted">Expenses</div><div className="metric">{o.currency} {expense.toLocaleString()}</div></div><div className="card"><div className="muted">Balance</div><div className="metric">{o.currency} {(income-expense).toLocaleString()}</div></div><div className="card"><div className="muted">Transactions</div><div className="metric">{rows?.length||0}</div></div></div><section className="section"><div className="card"><div className="section-title">Recent transactions</div>{rows?.length?<div className="table">{rows.map((x:{id:string,transaction_type:string,category:string,description:string|null,amount:number,transaction_date:string})=><div className="table-row" key={x.id}><strong>{x.transaction_date}</strong><span>{x.transaction_type}</span><span>{x.category}</span><span>{o.currency} {Number(x.amount).toLocaleString()}</span></div>)}</div>:<p className="subtitle">No financial transactions recorded yet.</p>}</div></section></main>;
}