"use client";
import { FormEvent, useState } from "react";
import Link from "next/link";
import { createClient } from "../../../lib/supabase/client";
export default function NewPerson({searchParams}:{searchParams:Promise<{org?:string}>}) {
 const [org,setOrg]=useState(""); const [name,setName]=useState(""); const [type,setType]=useState("contact"); const [email,setEmail]=useState(""); const [phone,setPhone]=useState(""); const [message,setMessage]=useState(""); const [loading,setLoading]=useState(false);
 useEffect(()=>{searchParams.then(p=>setOrg(p.org||""));},[searchParams]);
 async function submit(e:FormEvent){e.preventDefault();if(!org){setMessage("An organization is required.");return;}setLoading(true);const {error}=await createClient().from("people").insert({organization_id:org,full_name:name,person_type:type,email,phone});setLoading(false);if(error){setMessage(error.message);return}window.location.href="/people?org="+org}
 return <main className="main" style={{marginLeft:0,width:"100%",maxWidth:700,margin:"0 auto"}}><div className="topbar"><div><div className="eyebrow">People</div><h1 className="title">Add person</h1><div className="subtitle">Create a tenant-scoped people record.</div></div><Link className="button secondary" href={"/people?org="+org}>Back</Link></div><form className="card" onSubmit={submit}><div className="form-grid"><label>Full name<input required value={name} onChange={e=>setName(e.target.value)}/></label><label>Type<select value={type} onChange={e=>setType(e.target.value)}><option>contact</option><option>employee</option><option>student</option><option>customer</option><option>supplier</option><option>member</option></select></label><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Phone<input value={phone} onChange={e=>setPhone(e.target.value)}/></label></div><button className="button" disabled={loading}>{loading?"Saving...":"Save person"}</button>{message&&<p className="subtitle">{message}</p>}</form></main>
}