"use client";
import { FormEvent,useEffect,useState } from "react";
import Link from "next/link";
import { createClient } from "../../../lib/supabase/client";
export default function NewInventory({searchParams}:{searchParams:Promise<{org?:string}>}) {
 const [org,setOrg]=useState("");const [name,setName]=useState("");const [sku,setSku]=useState("");const [category,setCategory]=useState("");const [unit,setUnit]=useState("piece");const [quantity,setQuantity]=useState("0");const [reorder,setReorder]=useState("0");const [cost,setCost]=useState("0");const [message,setMessage]=useState("");const [loading,setLoading]=useState(false);
 useEffect(()=>{searchParams.then(p=>setOrg(p.org||""));},[searchParams]);
 async function submit(e:FormEvent){e.preventDefault();if(!org){setMessage("An organization is required.");return;}setLoading(true);const {error}=await createClient().from("inventory_items").insert({organization_id:org,name,sku,category,unit,quantity:Number(quantity),reorder_level:Number(reorder),unit_cost:Number(cost)});setLoading(false);if(error){setMessage(error.message);return}window.location.href="/inventory?org="+org}
 return <main className="main" style={{marginLeft:0,width:"100%",maxWidth:760,margin:"0 auto"}}><div className="topbar"><div><div className="eyebrow">Inventory</div><h1 className="title">Add inventory item</h1><div className="subtitle">Create a product or stock item.</div></div><Link className="button secondary" href={"/inventory?org="+org}>Back</Link></div><form className="card" onSubmit={submit}><div className="form-grid"><label>Item name<input required value={name} onChange={e=>setName(e.target.value)}/></label><label>SKU<input value={sku} onChange={e=>setSku(e.target.value)}/></label><label>Category<input value={category} onChange={e=>setCategory(e.target.value)}/></label><label>Unit<input value={unit} onChange={e=>setUnit(e.target.value)}/></label><label>Quantity<input min="0" step="0.001" type="number" value={quantity} onChange={e=>setQuantity(e.target.value)}/></label><label>Reorder level<input min="0" step="0.001" type="number" value={reorder} onChange={e=>setReorder(e.target.value)}/></label><label>Unit cost<input min="0" step="0.01" type="number" value={cost} onChange={e=>setCost(e.target.value)}/></label></div><button className="button" disabled={loading}>{loading?"Saving...":"Save item"}</button>{message&&<p className="subtitle">{message}</p>}</form></main>
}