import Link from "next/link";
import { createClient } from "../../lib/supabase/server";
import WorkspaceNav from "../_components/WorkspaceNav";
export default async function Inventory({searchParams}:{searchParams:Promise<{org?:string}>}) {
 const p=await searchParams,s=await createClient(),{data:orgs}=await s.rpc("my_organizations"),o=orgs?.find((x:{id:string})=>x.id===p.org)||orgs?.[0];
 if(!o)return <main className="main"><div className="card"><h1 className="title">Inventory</h1><Link className="button" href="/onboarding">Create organization</Link></div></main>;
 const {data:canView}=await s.rpc("has_org_permission",{org_id:o.id,permission_key:"inventory.view"}); if(!canView)return <main className="main"><div className="card"><h1 className="title">Access denied</h1><p className="subtitle">You do not have permission to view inventory.</p></div></main>;
 const {data:items}=await s.from("inventory_items").select("id,name,sku,category,unit,quantity,reorder_level,unit_cost,is_active").eq("organization_id",o.id).order("name");
 const stockValue=(items||[]).reduce((a,x)=>a+Number(x.quantity)*Number(x.unit_cost),0),low=(items||[]).filter((x:{quantity:number,reorder_level:number})=>Number(x.quantity)<=Number(x.reorder_level)).length;
 return <main className="main" style={{marginLeft:0,width:"100%",maxWidth:1100,margin:"0 auto"}}><div className="topbar"><div><div className="eyebrow">Inventory</div><h1 className="title">{o.name}</h1><div className="subtitle">Products, stock levels and inventory value.</div></div><div style={{display:"flex",gap:8}}><Link className="button" href={"/inventory/new?org="+o.id}>Add item</Link><Link className="button secondary" href={"/dashboard?org="+o.id}>Dashboard</Link></div></div><WorkspaceNav org={o.id}/><div className="grid"><div className="card"><div className="muted">Items</div><div className="metric">{items?.length||0}</div></div><div className="card"><div className="muted">Low stock</div><div className="metric">{low}</div></div><div className="card"><div className="muted">Stock value</div><div className="metric">{o.currency} {stockValue.toLocaleString()}</div></div><div className="card"><div className="muted">Status</div><div className="metric">Live</div></div></div><section className="section"><div className="card"><div className="section-title">Inventory items</div>{items?.length?<div className="table">{items.map((x:{id:string,name:string,sku:string|null,category:string|null,unit:string,quantity:number,reorder_level:number,unit_cost:number})=><div className="table-row" key={x.id}><strong>{x.name}</strong><span>{x.sku||"—"}</span><span>{Number(x.quantity).toLocaleString()} {x.unit}</span><span>{x.category||"Uncategorized"}</span></div>)}</div>:<p className="subtitle">No inventory items have been added yet.</p>}</div></section></main>;
}