"use client";
import { FormEvent,useEffect,useState } from "react";
import Link from "next/link";
import { createClient } from "../../../lib/supabase/client";
export default function NewFinance({searchParams}:{searchParams:Promise<{org?:string}>}) {
 const [org,setOrg]=useState("");const [type,setType]=useState("income");const [category,setCategory]=useState("");const [description,setDescription]=useState("");const [amount,setAmount]=useState("");const [date,setDate]=useState(new Date().toISOString().slice(0,10));const [message,setMessage]=useState("");const [loading,setLoading]=useState(false);
 useEffect(()=>{searchParams.then(p=>setOrg(p.org||""));},[searchParams]);
 async function submit(e:FormEvent){e.preventDefault();if(!org){setMessage("An organization is required.");return;}setLoading(true);const supabase=createClient();const {data:{user}}=await supabase.auth.getUser();if(!user){window.location.href="/login";return;}const {data:allowed}=await supabase.rpc("has_org_permission",{org_id:org,permission_key:"finance.manage"});if(!allowed){setLoading(false);setMessage("You do not have permission to manage finance records.");return;}const {error}=await supabase.from("finance_transactions").insert({organization_id:org,transaction_type:type,category,description,amount:Number(amount),transaction_date:date,created_by:user?.id});setLoading(false);if(error){setMessage(error.message);return}window.location.href="/finance?org="+org}
 return <main className="main" style={{marginLeft:0,width:"100%",maxWidth:700,margin:"0 auto"}}><div className="topbar"><div><div className="eyebrow">Finance</div><h1 className="title">Record transaction</h1><div className="subtitle">Add income or expense to the organization ledger.</div></div><Link className="button secondary" href={"/finance?org="+org}>Back</Link></div><form className="card" onSubmit={submit}><div className="form-grid"><label>Transaction type<select value={type} onChange={e=>setType(e.target.value)}><option>income</option><option>expense</option></select></label><label>Category<input required value={category} onChange={e=>setCategory(e.target.value)} placeholder="Sales, rent, salary..." /></label><label>Amount<input required min="0" step="0.01" type="number" value={amount} onChange={e=>setAmount(e.target.value)}/></label><label>Date<input required type="date" value={date} onChange={e=>setDate(e.target.value)}/></label></div><label>Description<input value={description} onChange={e=>setDescription(e.target.value)}/></label><button className="button" disabled={loading}>{loading?"Saving...":"Save transaction"}</button>{message&&<p className="subtitle">{message}</p>}</form></main>
}