import Link from "next/link";
import { createClient } from "../../../lib/supabase/server";
import { modules } from "../../../lib/modules";
export default async function ModuleOperation({params,searchParams}:{params:Promise<{module:string}>,searchParams:Promise<{org?:string}>}) {
 const [p,q]=await Promise.all([params,searchParams]),s=await createClient(),{data:orgs}=await s.rpc("my_organizations"),o=orgs?.find((x:{id:string})=>x.id===q.org)||orgs?.[0],m=modules.find(x=>x.id===p.module);
 if(!o||!m)return <main className="main"><div className="card"><h1 className="title">Module not found</h1><Link className="button" href="/dashboard">Dashboard</Link></div></main>;
 const {data:enabled}=await s.from("organization_modules").select("module_key").eq("organization_id",o.id).eq("module_key",m.id).eq("enabled",true).maybeSingle();
 if(!enabled)return <main className="main"><div className="card"><h1 className="title">Module not enabled</h1><p className="subtitle">Enable this module from organization settings.</p><Link className="button" href={"/settings?org="+o.id}>Settings</Link></div></main>;
 const descriptions:Record<string,string>={school:"Students, teachers, classes, subjects, attendance, exams and fees.",restaurant:"Tables, menu, orders, kitchen, cashier and restaurant inventory.",office:"Employees, departments, projects, tasks, meetings and company assets.",ngo:"Programs, beneficiaries, donors, activities, monitoring and impact.",retail:"Products, point of sale, stock, customers and sales.",hotel:"Guests, rooms, bookings, housekeeping and payments.",clinic:"Patients, appointments, services, records and payments.",warehouse:"Warehouses, stock movements, receiving, dispatch and suppliers.","service-business":"Clients, service jobs, appointments, staff and payments."};
 return <main className="main" style={{marginLeft:0,width:"100%",maxWidth:1000,margin:"0 auto"}}><div className="topbar"><div><div className="eyebrow">Industry module</div><h1 className="title">{m.name}</h1><div className="subtitle">{o.name}</div></div><Link className="button secondary" href={"/operations?org="+o.id}>Operations</Link></div><div className="card"><div className="section-title">Module workspace</div><p className="subtitle">{descriptions[m.id]||m.description}</p><div className="modules" style={{marginTop:18}}><div className="module"><h3>Overview</h3><p>Operational dashboard for this module.</p></div><div className="module"><h3>Records</h3><p>Manage module-specific records.</p></div><div className="module"><h3>Reports</h3><p>Review activity and performance.</p></div></div></div></main>;
}